version: "3.8"
services:
  eureka:
    image: andergi/eureka:latest
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - "netAlumnos"
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=tiger
      - MYSQL_DATABASE=actividad17
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=tiger
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - "netAlumnos"
  alumnos:
    image: andergi/alumnos:latest
    container_name: alumnos
    ports:
      - "8001:8001"
    depends_on:
      - "mysql"
      - "eureka"
    networks:
      - "netAlumnos"
  modulos:
    image: andergi/modulos:latest
    container_name: modulos
    ports:
      - "8011:8011"
    depends_on:
      - "mysql"
      - "eureka"
    networks:
      - "netAlumnos"
  notas:
    image: andergi/notas:latest
    container_name: notas
    ports:
      - "8111:8111"
    depends_on:
      - "mysql"
      - "eureka"
    networks:
      - "netAlumnos"
networks:
  netAlumnos:
    driver: bridge
